prediction_type: "" # depletion | incremental
model_name: ""
model_export_dir: ""

#config that not matching type are not being used in this training
# "*" for all file in directory
dataset_config:
  dataset_dir: ""
  dataset_files:
    - "*" 
  timestamp_col: "timestamp"
  value_col: "value"

prediction_boundary:
  floor_value: 0 # bottom limit
  ceiling_value: 0 # top limit

lstm_config:
  windows_size: 24
  units: [64, 32]
  dropout: 0.2
  epochs: 50
  batch_size: 32

#Optional
transfer_training:
  base_dir: ""
  model_list:
    - "*"

#Future improvement
#fine_tune: